import Head from 'next/head';
import { Header } from '../components/Header';

export default function Home() {
  return (
    <>
      <Head>
        <title>Andres Argote | Frontend developer</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='container flex items-center justify-center h-screen max-w-xl p-4 mx-auto sm:p-0'>
        <main className='w-full p-6 bg-white rounded-lg shadow-lg'>
          <Header />
        </main>
      </div>
    </>
  );
}
