import Head from 'next/head';
import { ContactMe } from '../components/ContactMe';
import { Header } from '../components/Header';
import { LastProjects } from '../components/LastProjects';
import { LastWork } from '../components/LastWork';

export default function Home() {
  return (
    <>
      <Head>
        <title>Andres Argote | Frontend developer</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='container flex items-center justify-center max-w-xl p-4 mx-auto mt-4 sm:h-screen sm:p-0 sm:mt-0'>
        <div className='w-full bg-white rounded-lg shadow-lg '>
          <main className='p-6'>
            <Header />
            <LastWork />
            <LastProjects />
            <div className='container flex justify-center mt-4'>
              <ContactMe />
            </div>
          </main>
        </div>
      </div>
    </>
  );
}
